# Generated by Django 4.2.11 on 2024-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
