# Generated by Django 4.2.11 on 2024-04-19 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_board_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='likes',
        ),
        migrations.AddField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
